### ISSUE TITLE
Displaying folder size in the folder explorer modal.

### ISSUE THREAD

**Issue by agatha197** [lablup/backend.ai-webui#1980] opened 2023-10-20 11:01 UTC
### What Operating System(s) are you seeing this problem on?

macOS (Apple Silicon)

### Backend.AI version

f6c3964

### Describe the bug

If a user uploads a folder, every folder size in the folder explorer modal is the same. Let's represent it in the correct size of the folder.
![image](https://github.com/lablup/backend.ai-webui/assets/28584164/65559487-f346-45c9-9690-276554da9ae7)

### To Reproduce

Upload any folder using the folder upload feature in the file explorer.

### Expected Behavior

Display folder size.

**Comment by lizable** [comment] 2023-11-10 01:19
Closing this issue duplicate of #1988.

**Closed by lizable** 2023-11-10 01:19 UTC
Labels: type:fix, effort:normal, area:ux, urgency:3, platform:general, impact:visible, field:UI / UX
